/* Auto-generated — DO NOT EDIT */
/* Placeholder: 440Hz beep, 0.2s, 44100Hz, 16-bit mono */
/* Replace this with your own WAV generated by host_tool/mp3_to_c_array.py */
#ifndef G_POWER_ON_WAV_H
#define G_POWER_ON_WAV_H

#include <stdint.h>

extern const uint8_t  g_power_on_wav[];
extern const uint32_t g_power_on_wav_size;

#endif /* G_POWER_ON_WAV_H */
