/* Auto-generated by mp3_to_c_array.py — DO NOT EDIT */
/* Source: off2.mp3  Size: 204931 bytes  Volume: 53% */
#ifndef G_REMIND_OFF2_H
#define G_REMIND_OFF2_H

#include <stdint.h>

extern const uint8_t  g_remind_off2[];
extern const uint32_t g_remind_off2_size;

#endif /* G_REMIND_OFF2_H */
