/* Auto-generated by mp3_to_c_array.py — DO NOT EDIT */
/* Source: on.mp3  Size: 286720 bytes  Volume: 60% */
#ifndef G_REMIND_ON_H
#define G_REMIND_ON_H

#include <stdint.h>

extern const uint8_t  g_remind_on[];
extern const uint32_t g_remind_on_size;

#endif /* G_REMIND_ON_H */
