#ifndef __ERR_HANDLE_H__
#define __ERR_HANDLE_H__

typedef enum {
    SUCCESS = 0,
    ENABLE_INVALID_INPUT,
    SAMPLE_INVALID_INPUT,
    ENABLE_OUT_OF_MEMORY,
    ENABLE_INVALID_INPUT_RANGE,
    ENABLE_DEVICE_NOT_READY,
    ENABLE_OPERATION_FAILED,
    ENABLE_CHECKSUM_ERROR,
    ENABLE_TIMEOUT,
    ENABLE_NOT_FOUND,
    ENABLE_ALREADY_EXISTS,
    ENABLE_PERMISSION_DENIED,
    ENABLE_NOT_SUPPORTED,
    ENABLE_BUSY,
    ENABLE_IO_ERROR,
    ENABLE_FORMAT_ERROR,
    ENABLE_CORRUPTION,
    ENABLE_OVERFLOW,
    ENABLE_UNDERFLOW,
    ENABLE_ALIGNMENT_ERROR,
    ENABLE_STATE_ERROR,
    ENABLE_CONFIG_ERROR,
    ENABLE_RESOURCE_ERROR,
    ENABLE_PROTOCOL_ERROR,
    ENABLE_HARDWARE_ERROR,
    ENABLE_SOFTWARE_ERROR,
    ENABLE_UNKNOWN_ERROR
} BG_ERR;

#endif
