#!/usr/bin/env python3
"""Generate a WAV C-array for power-on music (440Hz beep, 0.2s)."""
import struct, math, os

# --- Config ---
SAMPLE_RATE = 44100
DURATION    = 0.2          # seconds
FREQ        = 440          # Hz (A4 note)
AMPLITUDE   = 28000        # ~85% of 16-bit max

OUT_DIR = os.path.join(os.path.dirname(__file__), "..",
                       "BanBox", "src", "banux", "06_app", "power_on_music")

# --- Build WAV bytes ---
num_samples = int(SAMPLE_RATE * DURATION)
pcm_bytes = bytearray()

for i in range(num_samples):
    t = i / SAMPLE_RATE
    sample = int(AMPLITUDE * math.sin(2 * math.pi * FREQ * t))
    pcm_bytes += struct.pack('<h', sample)

# Apply fade in/out (10ms each)
fade_len = int(SAMPLE_RATE * 0.01)
for i in range(fade_len):
    factor = i / fade_len
    sample = struct.unpack('<h', pcm_bytes[i*2:(i+1)*2])[0]
    pcm_bytes[i*2:(i+1)*2] = struct.pack('<h', int(sample * factor))
for i in range(fade_len):
    idx = num_samples - 1 - i
    factor = i / fade_len
    sample = struct.unpack('<h', pcm_bytes[idx*2:(idx+1)*2])[0]
    pcm_bytes[idx*2:(idx+1)*2] = struct.pack('<h', int(sample * factor))

# WAV header
data_size = len(pcm_bytes)
wav = struct.pack('<4sI4s', b'RIFF', 36 + data_size, b'WAVE')
wav += struct.pack('<4sIHHIIHH',
    b'fmt ', 16,           # subchunk1 size
    1, 1,                  # PCM, mono
    SAMPLE_RATE,           # sample rate
    SAMPLE_RATE * 2,       # byte rate
    2, 16)                 # block align, bits per sample
wav += struct.pack('<4sI', b'data', data_size)
wav += pcm_bytes

print(f"WAV: {len(wav)} bytes, {num_samples} samples, {DURATION}s @ {SAMPLE_RATE}Hz")

# --- Write .h ---
hdr = f'''/* Auto-generated — DO NOT EDIT */
/* Placeholder: 440Hz beep, {DURATION}s, {SAMPLE_RATE}Hz, 16-bit mono */
/* Replace this with your own WAV generated by host_tool/mp3_to_c_array.py */
#ifndef G_POWER_ON_WAV_H
#define G_POWER_ON_WAV_H

#include <stdint.h>

extern const uint8_t  g_power_on_wav[];
extern const uint32_t g_power_on_wav_size;

#endif /* G_POWER_ON_WAV_H */
'''

# --- Write .c ---
lines = ['/* Auto-generated — DO NOT EDIT */', '#include "g_power_on_wav.h"', '']
lines.append(f'const uint32_t g_power_on_wav_size = {len(wav)};')
lines.append('')
lines.append('const uint8_t g_power_on_wav[] = {')

byte_strs = [f'0x{b:02X}' for b in wav]
for i in range(0, len(byte_strs), 16):
    chunk = byte_strs[i:i+16]
    prefix = '    ' if i == 0 else '    '
    suffix = '' if i + 16 >= len(byte_strs) else ''
    lines.append(prefix + ', '.join(chunk) + ',')

lines.append('};')
lines.append('')

os.makedirs(OUT_DIR, exist_ok=True)
with open(os.path.join(OUT_DIR, 'g_power_on_wav.h'), 'w', encoding='utf-8') as f:
    f.write(hdr)
with open(os.path.join(OUT_DIR, 'g_power_on_wav.c'), 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Written: g_power_on_wav.h, g_power_on_wav.c  →  {OUT_DIR}")
