/* Auto-generated by mp3_to_c_array.py — DO NOT EDIT */
/* Source: power_on.wav  Size: 706254 bytes  Volume: 41% */
#ifndef G_REMIND_POWER_ON_H
#define G_REMIND_POWER_ON_H

#include <stdint.h>

extern const uint8_t  g_remind_power_on[];
extern const uint32_t g_remind_power_on_size;

#endif /* G_REMIND_POWER_ON_H */
