################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/adc_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/backup_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/dac_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/fft_api.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/i2c_host.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/i2c_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/sadc_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/sd_card.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/spim_interface.c \
C:/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/uarts_interface.c 

OBJS += \
./driver/driver_api/src/adc_interface.o \
./driver/driver_api/src/backup_interface.o \
./driver/driver_api/src/dac_interface.o \
./driver/driver_api/src/fft_api.o \
./driver/driver_api/src/i2c_host.o \
./driver/driver_api/src/i2c_interface.o \
./driver/driver_api/src/sadc_interface.o \
./driver/driver_api/src/sd_card.o \
./driver/driver_api/src/spim_interface.o \
./driver/driver_api/src/uarts_interface.o 

C_DEPS += \
./driver/driver_api/src/adc_interface.d \
./driver/driver_api/src/backup_interface.d \
./driver/driver_api/src/dac_interface.d \
./driver/driver_api/src/fft_api.d \
./driver/driver_api/src/i2c_host.d \
./driver/driver_api/src/i2c_interface.d \
./driver/driver_api/src/sadc_interface.d \
./driver/driver_api/src/sd_card.d \
./driver/driver_api/src/spim_interface.d \
./driver/driver_api/src/uarts_interface.d 


# Each subdirectory must supply rules for building sources it contributes
driver/driver_api/src/adc_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/adc_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/backup_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/backup_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/dac_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/dac_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/fft_api.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/fft_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/i2c_host.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/i2c_host.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/i2c_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/i2c_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/sadc_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/sadc_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/sd_card.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/sd_card.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/spim_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/spim_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

driver/driver_api/src/uarts_interface.o: /cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/src/uarts_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: Andes C Compiler'
	$(CROSS_COMPILE)gcc -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/mv_utils/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/driver/driver_api/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/freertos/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Encoder" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_flash_manager" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/BG_Lcd" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/audio/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/USB/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/rtos/rtos_api" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/MVsB1_Base_SDK/middleware/fatfs/inc" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/base_func" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/BG_List" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/BanGUI/page" -I"/cygdrive/C/Users/Hasee/Desktop/BG_Audio_Looper2/BG_card_RTOS/src/hardware/audio_looper" -Og -mcmodel=medium -g3 -Wall -mcpu=d1088-spu -c -fmessage-length=0 -ldsp -mext-dsp -fsingle-precision-constant -ffunction-sections -fdata-sections -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d) $(@:%.o=%.o)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


